- donggle/donggle.xcodeproj/project.pbxproj
- donggle/donggle/testView.swift
create testView. test pbxproj conflict
> test conflict

- donggle/donggle.xcodeproj/project.pbxproj
- donggle/donggle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- donggle/donggle/Views/GiftCheckView.swift
- donggle/donggle/Views/TimelineView.swift
- TimelineView 파일 수정
- GiftCheckView 파일 추가
> Add timeline, gift check view

- donggle/donggle/Tab bar Views/HomeView.swift
- donggle/donggle/Views/RecordTestingView.swift
- donggle/donggle/Views/RecordView.swift
HomeView에 있는 버튼으로 RecordView 모달 연결
동글이 색깔 수식 변경
스트레스 지수 변화 반영
> #27 feat:HomeView와 RecordView연결 (동글이 색깔, 스트레스 지수 변화 반영)

- donggle/donggle.xcodeproj/project.pbxproj
- donggle/donggle/Views/CardDetailView.swift
- donggle/donggle/Views/DetailCard/DetailCardBack.swift
- donggle/donggle/Views/DetailCard/DetailCardFront.swift
> #34 [Feat] 보상카드 상세보기 및 카드 뒤집기

- donggle/donggle/Tab bar Views/CalenderView.swift
> #36 Feat : 보상 캘린더 userDefault 데이터 추가 및 기능 연동

- donggle/donggle.xcodeproj/project.pbxproj
- donggle/donggle/Tab bar Views/ReportView.swift
- donggle/donggle/Views/ModalView.swift
- donggle/donggle/Views/ProgressBar.swift
- donggle/donggle/Views/RewardCard2.swift
- donggle/donggle/Views/RewardReportView.swift
- donggle/donggle/Views/StressReportView.swift
- donggle/donggle/Views/TabBarView.swift
- donggle/donggle/Views/UpperTab/CustomTapView.swift
> Refact: ReportView 리팩토링

- donggle/donggle/Model/SRdata.swift
- donggle/donggle/Tab bar Views/CalenderView.swift
- donggle/donggle/Tab bar Views/HomeView.swift
- donggle/donggle/Views/RecordView.swift
- donggle/donggle/Views/TabBarView.swift
> 제일 최신 버전 입니다.

- donggle/donggle/Views/ProgressBar.swift
- donggle/donggle/Views/RewardCard2.swift
- donggle/donggle/Views/RewardReportView.swift
- donggle/donggle/Views/StressReportView.swift
Feat: 누적 리스트 누적량 정렬 + 같은 경우 이름순 정렬 기능 추가
름
> Feat: 누적 리스트 누적량 정렬 + 같은 경우 이름순 정렬 기능 추가

- donggle/donggle.xcodeproj/project.pbxproj
- donggle/donggle/Model/SRdata.swift
- donggle/donggle/Model/StyleData.swift
- donggle/donggle/Views/CardDetailView.swift
- donggle/donggle/Views/GiftCheckView.swift
- donggle/donggle/Views/RecordView.swift
- donggle/donggle/Views/UpdateRewardView.swift
> [Feat] GiftCheckView와 UpdateView #76 #77

- donggle/donggle/Tab bar Views/HomeView.swift
- donggle/donggle/Views/DetailCard/DetailCardBack.swift
- donggle/donggle/Views/GiftCheckView.swift
- donggle/donggle/Views/RecordView.swift
동글이 색상 노랑 -> 빨강으로 변경
기록할 떄 보상 추가만 하는 경우 다르게 저장하도록 조건문 변경
> [Refactor]동글이 색상변경 및 기록 뷰 저장 조건문 변경

- donggle/donggle/Model/SRdata.swift
- donggle/donggle/Views/GiftCheckView.swift
- donggle/donggle/Views/RecordRewardView.swift
- donggle/donggle/Views/RecordView.swift
스트레스 보상, 기록페이지 조건문 변경 (보상만 추가 가능)
GiftCheckView 동글이 부분 디자인 변경
> [Fix] 스트레스,보상 기록페이지 조건문 변경

- donggle/donggle.xcodeproj/project.pbxproj
- donggle/donggle/Views/CardDetailView.swift
- donggle/donggle/Views/GiftCheckView.swift
GiftCheckView에 Reward 데이터를 가져와 데이터 연동을 하였습니다. (isEffective true false 변경 가능)
- GiftCheckView, CardDetailView
> [Refactor] GiftCheckView 데이터 연동

- donggle/donggle.xcodeproj/project.pbxproj
- donggle/donggle/Tab bar Views/ReportView.swift
- donggle/donggle/Views/ModalView.swift
- donggle/donggle/Views/ProgressBar.swift
- donggle/donggle/Views/RewardCard2.swift
- donggle/donggle/Views/RewardReportView.swift
- donggle/donggle/Views/StressReportView.swift
- donggle/donggle/Views/TabBarView.swift
- donggle/donggle/Views/TimelineView.swift
- donggle/donggle/Views/UpperTab/CustomTapView.swift
- donggle/donggle/Views/UpperTab/CustomTopTabBar.swift
월별로 데이터 연동
- 차트
- 누적바
- 누적 리스트
- Top6 보상
- 누적바
- 누적리스트
> [Feat] 월별 차트, 누적 리스트, Top6 보상 데이터 연동

- donggle/donggle/Views/TimelineView.swift
디자인 변경
- 카드 레이아웃 다 변경했고, 동글이 색깔, 카테고리 나열  등 디자인 부분은 다 수정했습니다
> #71 [Design] 타임라인 디자인 수정

- donggle/donggle/Views/RewardReportView.swift
> Fix: RewardView data 없을 때 오류 수정

- donggle/donggle/Views/TimelineView.swift
> [Fix] 타임라인 modal show bug

- donggle/donggle/Views/RewardReportView.swift
- donggle/donggle/Views/StressReportView.swift
- donggle/donggle/Views/TimelineView.swift
> Fix: 버그 수정

- donggle/donggle/Views/TimelineView.swift
타임라인 날짜 표시 & 카테고리 배경색 적용 : 타임라인 전체 기능 구현 완료
- 날짜별로 카드 그룹화하여 표시
- 스트레스 카테고리에 따라 배경색 적용
- 디자인 일부 수정
* resolved : #89
> [Feat] 타임라인 날짜 표시 & 카테고리 배경색 적용

- donggle/donggle/Tab bar Views/HomeView.swift
- donggle/donggle/Views/DetailCard/DetailCardBack.swift
- donggle/donggle/Views/GiftCheckView.swift
- donggle/donggle/Views/RecordView.swift
- donggle/donggle/Views/StressReportView.swift
- donggle/donggle/Views/TabBarView.swift
- donggle/donggle/Views/TimelineView.swift
@yungahui  DetailBackView 데이터 바인딩 했어요 !
> [Design & Fix] RecordView 레이아웃, 모든 뷰에 동글이 표정 추가, DetailBackView 데이터 바인딩

- donggle/donggle/Tab bar Views/HomeView.swift
> [Design] HomeView 동글이 사이즈 변경

- donggle/donggle/Views/CardDetailView.swift
- donggle/donggle/Views/DetailCard/DetailCardBack.swift
- donggle/donggle/Views/DetailCard/DetailCardFront.swift
동글이 위치를 다시 설정하고, 보상 이모티콘 크기를 키웠습니다
스트레스 카테고리와 색상을 연결했습니다
- 변경/리뷰 파일이름
> #34 [Design] 요소 위치 수정 및 카테고리 연결

- donggle/donggle/Model/SRdata.swift
- donggle/donggle/Views/RecordView.swift
카테고리 글씨/목록 수정
SRdata RecordView 수정
> 카테고리 글씨/목록 수정

- donggle/donggle/Model/SRdata.swift
- donggle/donggle/Model/StyleData.swift
- donggle/donggle/Views/RecordView.swift
> keyboard tap disappear
